config/routes.rb
# frozen_string_literal: true

Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :favorites, only: :index do
      get :users, on: :member
    end
  end

  resources :favorites, only: [:index, :create, :destroy]
end

app/models/spree/favorite.rb
# frozen_string_literal: true

module Spree
  class Favorite < ApplicationRecord
    FAVORABLES_ALLOWED = [
      'Spree::Product'
    ].freeze

    belongs_to :favorable, polymorphic: true
    belongs_to :user, class_name: Spree.user_class.to_s
    belongs_to :variant, class_name: 'Spree::Variant', optional: true

    validates :favorable, presence: true
    validates :favorable_type,
              presence: true,
              inclusion: {
                in: FAVORABLES_ALLOWED
              }

    validates :user_id,
              uniqueness: {
                allow_blank: true,
                message: 'Already added as favorite.',
                scope: [:favorable_id, :favorable_type]
              }
    validates :guest_token,
              uniqueness: {
                allow_blank: true,
                message: 'Already added as favorite.',
                scope: [:favorable_id, :favorable_type]
              }

    scope :by_guest_token, ->(token) { where(guest_token: token) }

    default_scope { order('created_at DESC') }
  end
end

app/controllers/spree/admin/favorites_controller.rb
# frozen_string_literal: true

module Spree
  module Admin
    class FavoritesController < Spree::Admin::BaseController
      def index
        @favorites = Spree::Product.joins(:favorites)
                                   .page(params[:page])
                                   .per(SolidusFavorites::Config.favorites_per_page)
      end

      def users
        @product = Spree::Product.where(id: params[:id]).first
        @users = @product.favorite_users
                         .page(params[:page])
                         .per(SolidusFavorites::Config.favorites_per_page)
      end
    end
  end
end

app/controllers/spree/favorites_controller.rb
# frozen_string_literal: true

module Spree
  class FavoritesController < Spree::StoreController
    helper SolidusFavorites::FavoritesHelper

    prepend_before_action :store_favorite_product_preference, only: :create
    before_action :authenticate_spree_user!
    before_action :favorite, only: [:destroy]

    respond_to :html, :js

    def index
      @favorites = try_spree_current_user.favorites
                                         .page(params[:page])
                                         .per(SolidusFavorites::Config.favorites_per_page) || []
    end

    def create
      @favorite = try_spree_current_user.favorites.new(favorite_params)

      if @favorite.save
        flash.now[:success] = t('spree.successfully_added_favorite')
      else
        flash.now[:error] = @favorite.errors.full_messages.to_sentence
      end

      respond_with(&:js)
    end

    def destroy
      if @favorite&.destroy
        flash.now[:success] = t('spree.favorite_successfully_removed')
      else
        flash.now[:error] = t('spree.favorite_unsuccessfully_removed')
      end

      respond_with(&:js)
    end

    private

    def favorite
      @favorite ||= try_spree_current_user.favorites.find(params[:id])
    end

    def favorite_params
      params.permit(:favorable_id, :favorable_type, :variant_id)
    end

    def model_class
      Spree::Favorite
    end

    def store_favorite_product_preference
      return if spree_current_user

      session[:spree_user_return_to] =
        product_url(id: params[:favorable_id], favorable_id: params[:favorable_id], favorable_type: params[:favorable_type])
      redirect_to login_path, notice: I18n.t('spree.login_to_add_favorite')
    end
  end
end

app/helpers/solidus_favorites/favorites_helper.rb
# frozen_string_literal: true

module SolidusFavorites
  module FavoritesHelper
    def favorite_price(favorite, options)
      if ::Spree.solidus_gem_version < Gem::Version.new('3.1')
        favorite&.favorable&.price_for(options)
      else
        favorite&.favorable&.price_for_options(options)&.money
      end
    end
  end
end

app/views/spree/admin/favorites/index.html.erb
<% admin_breadcrumb(link_to(plural_resource_name(Spree::Product), spree.admin_products_path)) %>
<% admin_breadcrumb(plural_resource_name(Spree::Favorite)) %>

<%= paginate @favorites, theme: 'solidus_admin' %>

<% if @favorites.any? %>
  <table class='index' id='listing_products'>
    <colgroup>
       <col style='width: 15%;'>
       <col style='width: 5%;'>
       <col style='width: 50%;'>
       <col style='width: 15%;'>
       <col style='width: 15%;'>
    </colgroup>

    <thead>
      <tr data-hook='admin_products_index_headers'>
        <th><%= t('spree.sku') %></th>
        <th colspan='2'><%= t('spree.name') %></th>
        <th class='align-center'><%= t('spree.master_price') %></th>
        <th class='align-center'><%= t('spree.favorite_users') %></th>
      </tr>
    </thead>

    <tbody>
      <% @favorites.each do |favorite| %>
        <tr <%== "style='color: red;'" if favorite.deleted? %> id='<%= spree_dom_id favorite %>' data-hook='admin_favorites_index_rows'>
          <td><%= favorite.sku %></td>
          <td class='align-center'>
            <% if favorite&.respond_to?(:gallery) %>
                <%= link_to(render('spree/shared/image', image: favorite&.gallery&.images&.first, size: :small), admin_product_path(favorite), itemprop: 'image') %>
              <% else %>
                <%= link_to(image_tag(favorite.display_image.attachment(:small), itemprop: 'image'), admin_product_path(favorite), itemprop: 'url') %>
              <% end %>
          </td>
          <td><%= link_to(favorite.try(:name), admin_product_path(favorite)) %></td>
          <td class='align-center'><%= favorite&.display_price.to_html %></td>
          <td class='align-center'><%= link_to favorite&.favorite_users.count, users_admin_favorite_path(id: favorite.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class='no-objects-found'>
    <%= t('spree.no_results') %>
  </div>
<% end %>

<%= paginate @favorites, theme: 'solidus_admin' %>

app/views/spree/admin/favorites/users.html.erb
<% admin_breadcrumb(link_to(plural_resource_name(Spree::Product), spree.admin_products_path)) %>
<% admin_breadcrumb(link_to(plural_resource_name(Spree::Favorite), spree.admin_favorites_path)) %>
<% admin_breadcrumb(t('spree.users')) %>

<% content_for :page_title do %>
  <%= t('spree.favorite_users') %>
<% end %>

<%= paginate @users, theme: 'solidus_admin' %>

<% if @users.any? %>
  <table class='index' id='listing_favorite_products_users'>
    <thead>
      <tr data-hook='admin_favorite_users_index_headers'>
        <th><%= t('spree.email') %></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr <%== "style='color: red;'" if user.discarded? %> id='<%= spree_dom_id user %>' data-hook='admin_favorite_users_index_rows'>
          <td>
            <%= user.email %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class='no-objects-found'>
    <%= t('spree.no_results') %>
  </div>
<% end %>

<%= paginate @users, theme: 'solidus_admin' %>

app/views/spree/favorites/_product_link.html.erb
<div itemprop='favorite' data-hook='favorite'>
  <% if favorite?(@product) %>
    <%= link_to_with_icon '',
                          t('spree.remove_favorite'),
                          favorite_path(get_favorite(@product),
                                        favorable_id: @product.id,
                                        favorable_type: 'Spree::Product'),
                          method: :delete,
                          no_text: true,
                          remote: true,
                          id: "favorable_product_#{@product.id}",
                          class: 'favorite_product_link fa fa-heart no-text with-tip',
                          data: { favorable_id: @product.id, favorable_type: 'Spree::Product' } %>
  <% else %>
    <%= link_to_with_icon '',
                          t('spree.add_favorite'),
                          favorites_path(favorable_id: @product.id,
                                         favorable_type: 'Spree::Product'),
                          method: :post,
                          no_text: true,
                          remote: true,
                          id: "favorable_product_#{@product.id}",
                          class: 'favorite_product_link fa fa-heart-o no-text with-tip',
                          data: { favorable_id: @product.id, favorable_type: 'Spree::Product' } %>
  <% end %>
</div>

app/views/spree/favorites/create.js.erb
<% if @favorite.persisted? %>
  var $el = document.querySelector("#favorable_<%= @favorite.favorable_type.demodulize.underscore %>_<%= @favorite.favorable_id %>");

  $el.href = '<%= raw favorite_path(@favorite, favorable_id: @favorite.favorable_id, favorable_type: @favorite.favorable_type) %>';
  $el.dataset.method = 'delete';
<% end %>

app/views/spree/favorites/destroy.js.erb
<% if @favorite.destroyed? %>
  var $el = document.querySelector("#favorable_<%= @favorite.favorable_type.demodulize.underscore %>_<%= @favorite.favorable_id %>");

  if ($el) {
    $el.href = '<%= raw favorites_path(favorable_id: @favorite.favorable_id, favorable_type: @favorite.favorable_type) %>';
    $el.dataset.method = 'post';
  } else {
    $("#favorite_<%= @favorite.id %>").remove();
  }
<% end %>

app/views/spree/favorites/index.html.erb
<div data-hook='account_my_favorite_products' class='account-my-favorite-products'>
  <h3><%= t('spree.my_favorites') %></h3>

  <% if @favorites.present? %>
    <table class='favorite-products order-summary'>
      <thead>
        <tr>
          <th class='favorite-product-image'><%= t('spree.image') %></th>
          <th class='favorite-product-name'><%= t('spree.name') %></th>
          <th class='favorite-product-price'><%= t('spree.price') %></th>
          <th class='favorite-product-action'><%= t('spree.action')%></th>
        </tr>
      </thead>

      <tbody>
        <% @favorites.each do |favorite| %>
          <tr class="favorite_item <%= cycle('even', 'odd') %>" id='favorite_<%= favorite.id %>' data-product-id='<%= favorite&.favorable&.id %>' data-variant-id='<%= favorite&.favorable&.master&.id %>'>
            <td class='favorite-product-image'>
              <% if favorite&.favorable&.respond_to?(:gallery) %>
                <%= link_to(render('spree/shared/image', image: favorite&.favorable&.gallery&.images&.first, size: :small), product_path(favorite&.favorable), itemprop: 'image') %>
              <% else %>
                <%= link_to(image_tag(favorite&.favorable.display_image.attachment(:small), itemprop: 'image'), product_path(favorite&.favorable), itemprop: 'url') %>
              <% end %>
            </td>

            <td class='favorite-product-name'>
              <%= favorite&.favorable.name %>
            </td>

            <td class='favorite-product-price'>
              <% if price = favorite_price(favorite, current_pricing_options) %>
                <span class="price selling" itemprop="price" content="<%= price.to_d %>">
                  <%= price.to_html %>
                </span>

                <span itemprop='priceCurrency' content='<%= current_pricing_options.currency %>'></span>
              <% end %>
            </td>

            <td class='favorite-product-actions'>
              <div class='favorite-product-actions-links'>
                <% if favorite.favorable.has_variants? %>
                  <%= link_to t('spree.go_to_product'), product_path(favorite.favorable), class: 'favorite_go_to_product_link' %>
                <% else %>
                  <%= link_to t('spree.add_to_cart'), '#', class: 'favorite_add_to_cart_link', remote: true %>
                <% end %>
                <%= link_to t('spree.remove'), favorite_path(favorite), class: 'favorite_remove_link', method: :delete, remote: true %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <div class='no-objects-found'>
      <p><%= t('spree.you_have_no_favorites_yet') %></p>
    </div>
  <% end %>

  <%= paginate @favorites %>
</div